# Consider using when upgraading to rabbit 3.13+ using Cuttlefish
plugins.rabbitmq_management = true
plugins.rabbitmq_prometheus = true
plugins.rabbitmq_stomp = true
plugins.rabbitmq_web_stomp = true
plugins.rabbitmq_mqtt = true
